version: 2.1

jobs:
  build:
    docker:
      - image: centos:centos7
        environment:
          USER: root
    steps:
      - run:
          name: Install deps
          command: |
            yum -y update && yum -y install git wget rsync which gettext bzip2 zlib-devel perl gcc gcc-c++ make cronie 
      - checkout
      - run:
          name: Make
          command: |
            make example -j 2
      - run:
          name: Install crontab
          command: |
            bin/update -y
      - run:
          name: Start webserver
          command: |
            nohup var/cron/webserver
      - run:
          name: Test webserver
          command: |
            wget --spider localhost:8080
      - run:
          name: Start gitea
          command: |
            nohup var/cron/gitea
      - run:
          name: Test gitea
          command: |
            wget --spider localhost:3000
